### ISSUE TITLE
Le fichier style.css est impossible à ouvrir car il est inexistant ou mal renseigné

### ISSUE THREAD

**Issue by GuyliannEngels** [LouisSimon862/louis-simon-blog#1]
Salut @LouisSimon862 

Je repars de ton mail pour débuter notre discussion 

> Bonjour/Bonsoir, 
Je suis Louis SIMON, étudiant en BAB2 biologie (190061), et je suis face à un problème étrange lors de l'utilisation de Rstudio.
Comme demandé, j'ai modifié mon blog en transformant la section "M.E.A.L" en article (ce qui n'a pas posé problème) et j'ai voulu changer la couleur de la barre de navigation de mon blog, c'est là que mon problème arrive. J'ai créé un fichier "style.css" avec les instructions nécessaires au changement de couleur, je le renseigne comme il le faut dans la section "site.yml", je fais mon commit/pull/push et tout se passe normalement mais lorsque je construis le site avec "Build website", j'ai un message d'erreur qui dit que le fichier style.css est impossible à ouvrir car il est inexistant ou mal renseigné. Ce message d'erreur provoque la suppression du fichier style.css et du sous-dossier dans lequel je mettais les images utilisées pour mon blog  (pourtant pas concerné par le changement de couleur) du dossier shared, je dois alors recommencer et télécharger à nouveau mes images. Malgré ce message d'erreur, le changement de couleur sur mon blog s'est quand même réalisé. 
Y-aurait-il quelque chose à faire pour pouvoir à nouveau modifier mon blog sans que cela entraîne une suppression systématique  de ces deux sous dossiers ?
J'ai éteint et rallumé la machine virtuelle et rien n'y fait.
Je joins une capture du message d'erreur.
Le lien de mon blog : https://louissimon862.github.io/louis-simon-blog/
Je vous remercie pour l'attention que vous accorderez à ce mail.

![Capture message d'erreur](https://user-images.githubusercontent.com/33956170/68276815-1eb80380-006e-11ea-8677-672e041146b7.PNG)

**Comment by GuyliannEngels** [comment]
Tout d'abord bravo, tu essayé de lire le message d'erreur. 

Quand j'affiche ton site web, je peux voir le changement de couleur, as tu réussi à corriger l'erreur par toi même ?

**Comment by LouisSimon862** [comment]
Non, j'ai essayé de classer autrement le dossier style.css pour voir si c'était l'emplacement le problème et rien ne change, dès que j'essaye d'apporter une modification à mon blog, il apparaît ce même message d'erreur et le fichier style.css se supprime, où qu'il soit. Pourtant, la modification de couleur s'est bien effectuée

**Comment by LouisSimon862** [comment]
Et maintenant l'icône que j'avais réussi à placer à droite du nom de mon blog ne s'affiche plus non plus

**Comment by LouisSimon862** [comment]
A présent, ce même message d'erreur apparaît dans la console au moment de knit pour avoir un aperçu des changements apportés. Il apparaît aussi dans la section Git toute une série de suppresions que je n'ai pas faites.
![Message d'erreur](https://user-images.githubusercontent.com/55578629/68314691-e25cc580-00b6-11ea-82f1-dfa01944e1ac.PNG)

**Comment by GuyliannEngels** [comment]
@LouisSimon862 , 

Est ce que tu peux me nommer comme collaborateur de ton blog afin que je regarde de plus près ton code. Pour ce faire, tu dois aller dans les settings de ton projet blog

**Comment by LouisSimon862** [comment]
@GuyliannEngels cela devrait être fait

**Comment by GuyliannEngels** [comment]
Merci de m'avoir ajouté comme collaborateur de ton projet. Je suis maintenant plus à même de t'aider efficacement .

Je viens de réaliser un push. J'ai supprimer le dossier doc puis recompiler ton site depuis 0. J'ai replacé le fichier style.css à la racine de ton projet. 

Par du principe que tu ne dois pas toucher au document placer dans le dossier doc. 

est ce que j'ai résolu tes différents soucis ?

**Comment by LouisSimon862** [comment]
@GuyliannEngels 
Oui, un grand merci, j'ai juste une dernière question, il reste apparemment des changements dans la section git qui m'empêchent de réaliser un pull de vos modifications. Mais si je réalise un commit de ces changements, cela va-t-il créer des conflits à plusieurs endroits du blog ? Si oui, faut-il que je commit et que je règle ces conflits ensuite ? 

![Capture](https://user-images.githubusercontent.com/55578629/68528549-9d25d700-02f4-11ea-862e-c57f9d2a631d.PNG)

**Comment by GuyliannEngels** [comment]
Salut @LouisSimon862 ,

la joie des conflits. Oui, tu dois réaliser un COMMIT de tes modifications puis un PULL et gérer ce conflit.
